### ISSUE TITLE
Intra-email word finder

### ISSUE THREAD

**Issue by BobArnold03** [xstefank/gmail-row-highlight#12]
Highlighting rows in "nice shiny colors" might be helpful to some, but not to me because the "*" does that. Would you be able to make an app which allows the viewer to tab through a viewed email to find  all occurrences of a keyword. For example if an email contains the words "foo" and "fum", the app would find, and highlight in "bright shiny colors",  all occurrences of "fum" withing an email being viewed which contained both "foo" and "fum". The emails that i'm scanning are numerous and long and its hard to find the "needle"/keyword in the "haystack"/long email. Tkx

**Comment by xstefank** [comment]
Hello @BobArnold03, the aim of this extension was to provide highlight in email overview that would work with keyboard shortcuts as all of the available extensions were based on mouse events. I think the app you've described would be possible to implement, however, it is not my intention to add it to this one. I think that what you've described can be achieved by gmail itself:

-- For example if an email contains the words "foo" and "fum"
This can be done by search bar -> typing "foo" AND "fum" should do the trick

-- the app would find, and highlight in "bright shiny colors", all occurrences of "fum" withing an email being viewed which contained both "foo" and "fum"
I checked and if you've do the above search the occurrences of both searched keywords are highlighted in the opened email. Additionally, Ctrl+F and typing one of keywordss should "change the color" of the occurrences of the searched word (which will be one of the two you've searched for in the gmail search)

I hope, this helps :). I don't intend to extend the functionality of this extension in any further features than email highlights.

**Comment by BobArnold03** [comment]
Martin,

Thanks for your kind reply with some great info in it. I had come to the
same conclusions as you after some "playing around" yesterday, however the
"Ctl+F function" is a great suggestion. I understand that you now work for
Microsoft; your response leaves me with a favorable impression of Microsoft
and GitHub.

Regards
Bob

**Comment by xstefank** [comment]
Hi @BobArnold03 that's great to hear :) However, I don't work neither for Microsoft neither for GH, currently I am employed at Red Hat ;) I will close this issue for reasons described above. Thank you for your suggestions!
